### ISSUE TITLE
My Raspberry Pi Kubernetes cluster

### ISSUE THREAD

**Issue by Marcus-Smallman** [alexellis/k8s-on-raspbian#3]
Cluster Description:
**Marcus Smallman' DIY Raspberry Pi Kubernetes Cluster**

Related URL (Blog Post):
**https://marcussmallman.io/2018/02/18/diy-rasberry-pi-kubernetes-cluster/**

A while ago I was inspired to create my own cluster from reading a bunch of online resources. The prep.sh script in this repo was very helpful. I decided to write up my experience so that other can use/learn from.

**Comment by alexellis** [comment]
👍 thank you
